### ISSUE TITLE
when I cd NiChartWebsite, then npm install ,it shows npm command not found

### ISSUE THREAD

**Issue by 190865** [georgeaidinis/NiChartWebsite#3]
```[tasklist]
### Tasks
```

**Comment by georgeaidinis** [comment]
You have to install node.js and npm to your system first. Maybe visit [npm](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm)  or try something like `sudo apt-get install npm`.

**Comment by georgeaidinis** [comment]
You have to install node.js and npm to your system first. Maybe visit [npm](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm)  or try something like `sudo apt-get install npm`.

**Comment by 190865** [comment]
thank U~~~

**Comment by 190865** [comment]
In the fourth step, I have been running for more than half an hour. I want to ask if it takes a while to connect this server?

**Comment by 190865** [comment]
![image](https://github.com/CBICA/NiChart_Website/assets/87567415/78270df8-3552-4d3b-90bc-bae80f260d1e)

**Comment by georgeaidinis** [comment]
Server is up, visit the link that your terminal says (0.0.0.0:3000) or http://localhost:3000/ .

**Comment by 190865** [comment]
Yes！！！It's OK, but there is a problem. 3000 has just been used, I opened it, but I didn't respond anywhere. After a while, the cloud platform was closed. Then I tried 3001 and found that it couldn't open .

**Comment by 190865** [comment]
![image](https://github.com/CBICA/NiChart_Website/assets/87567415/bee3caba-19ae-4133-9ade-a953677cdaa7)

**Comment by 190865** [comment]
![image](https://github.com/CBICA/NiChart_Website/assets/87567415/ad5d584c-15e3-4b59-ac0a-8d29b1a05c11)

**Comment by 190865** [comment]
![image](https://github.com/CBICA/NiChart_Website/assets/87567415/e9fd0355-9aa6-4ae1-a39a-680bbbe09e69)
